### ISSUE TITLE
Does it support screen share? 

### ISSUE THREAD

**Issue by Raj123456788** [SelfnessAid/Socket.io-WebRTC#2]
Hello There, 
                  Can this be used for screen share instead of camera? Sorry, I am from C# world trying to get an answer. Thanks!

**Comment by WebMobi59** [comment]
Hi, 
This is for iOS, support Swift&Objective-C.
For C#, I think you may can use Objective-C file or it's better to reference C# library.
Thanks.

**Comment by Raj123456788** [comment]
Hello There, Thank you for the reply. Can you tell me how can I get a .a like(libwebrtc.a) that will have a screencapture module? Any guidance is appreciated.

**Comment by WebMobi59** [comment]
hmm, I am not sure about it.
